### ISSUE TITLE
Staging site/branch tracking

### ISSUE THREAD

**Issue by edward-simpson** [Skywire/capistrano-magento2#8]
Some way of tracking what branch is checked out on a staging site, potentially to be compatible with Slack staging branch command

**Comment by Demoli** [comment]
This script is actually responsible for the data used by slack, I'll rebuild it to allow us to read capistrano repos as well

https://github.com/Skywire/list-staging-branches/blob/master/list-staging-branches.sh

**Comment by Demoli** [comment]
Done
